"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isValidGitHubUsername = exports.fetchUserActivityWithMetadata = exports.fetchUserActivity = exports.GitHubValidationError = exports.GitHubRateLimitError = exports.GitHubNotFoundError = exports.GitHubError = void 0;
var errors_1 = require("./errors");
Object.defineProperty(exports, "GitHubError", { enumerable: true, get: function () { return errors_1.GitHubError; } });
Object.defineProperty(exports, "GitHubNotFoundError", { enumerable: true, get: function () { return errors_1.GitHubNotFoundError; } });
Object.defineProperty(exports, "GitHubRateLimitError", { enumerable: true, get: function () { return errors_1.GitHubRateLimitError; } });
Object.defineProperty(exports, "GitHubValidationError", { enumerable: true, get: function () { return errors_1.GitHubValidationError; } });
var ingestion_1 = require("./ingestion");
Object.defineProperty(exports, "fetchUserActivity", { enumerable: true, get: function () { return ingestion_1.fetchUserActivity; } });
Object.defineProperty(exports, "fetchUserActivityWithMetadata", { enumerable: true, get: function () { return ingestion_1.fetchUserActivityWithMetadata; } });
var validation_1 = require("./validation");
Object.defineProperty(exports, "isValidGitHubUsername", { enumerable: true, get: function () { return validation_1.isValidGitHubUsername; } });
