"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const strict_1 = __importDefault(require("node:assert/strict"));
const node_test_1 = require("node:test");
const engine_1 = require("./engine");
const tier_1 = require("./tier");
(0, node_test_1.describe)('computeSlopScore', () => {
    (0, node_test_1.it)('applies recency weighting and produces deterministic score', () => {
        const now = new Date('2026-02-23T00:00:00.000Z');
        const events = [
            {
                id: 'a',
                type: 'commit',
                repo: 'octo/repo',
                sha: 'a',
                message: 'feat: generated by copilot',
                occurredAt: '2026-02-20T00:00:00.000Z',
            },
            {
                id: 'b',
                type: 'commit',
                repo: 'octo/repo',
                sha: 'b',
                message: 'refactor: cleanup',
                occurredAt: '2026-02-20T00:00:00.000Z',
            },
            {
                id: 'c',
                type: 'commit',
                repo: 'octo/repo',
                sha: 'c',
                message: 'docs: generated by chatgpt',
                occurredAt: '2025-10-20T00:00:00.000Z',
            },
        ];
        const result = (0, engine_1.computeSlopScore)(events, undefined, now);
        strict_1.default.equal(result.slop_score, 20);
        strict_1.default.equal(result.confidence, 'low');
    });
    (0, node_test_1.it)('does not flag technical cursor mentions as AI evidence', () => {
        const now = new Date('2026-02-28T00:00:00.000Z');
        const events = [
            {
                id: 'a',
                type: 'commit',
                repo: 'torvalds/uemacs',
                sha: '8bd72de',
                message: 'Always call update() if the buffer is marked for refresh. In particular, the cursor location affects scrolling behavior.',
                occurredAt: '2026-02-25T00:00:00.000Z',
                additions: 1,
                deletions: 1,
            },
        ];
        const result = (0, engine_1.computeSlopScore)(events, undefined, now);
        strict_1.default.equal(result.slop_score, 0);
        strict_1.default.deepEqual(result.analyzed_commits[0]?.flags, []);
    });
    (0, node_test_1.it)('does not flag plain tool mentions without attribution context', () => {
        const now = new Date('2026-02-28T00:00:00.000Z');
        const events = [
            {
                id: 'a',
                type: 'commit',
                repo: 'dollspace-gay/chainlink',
                sha: 'b842e80',
                message: 'make chainlink reminder hook blocking to force claude to use it',
                occurredAt: '2026-02-08T00:00:00.000Z',
            },
        ];
        const result = (0, engine_1.computeSlopScore)(events, undefined, now);
        strict_1.default.equal(result.slop_score, 0);
        strict_1.default.deepEqual(result.analyzed_commits[0]?.flags, []);
    });
    (0, node_test_1.it)('scores contextual AI usage as medium evidence', () => {
        const now = new Date('2026-02-28T00:00:00.000Z');
        const events = [
            {
                id: 'a',
                type: 'commit',
                repo: 'octo/repo',
                sha: 'a',
                message: 'refactor parser using claude for an initial draft',
                occurredAt: '2026-02-27T00:00:00.000Z',
            },
        ];
        const result = (0, engine_1.computeSlopScore)(events, undefined, now);
        strict_1.default.equal(result.slop_score, 21);
        strict_1.default.deepEqual(result.analyzed_commits[0]?.flags, ['ai_keyword']);
        strict_1.default.equal(result.top_signals[0], 'Commits with AI-attribution hints');
    });
    (0, node_test_1.it)('scores explicit AI attribution as strong evidence', () => {
        const now = new Date('2026-02-28T00:00:00.000Z');
        const events = [
            {
                id: 'a',
                type: 'commit',
                repo: 'octo/repo',
                sha: 'a',
                message: 'docs: generated by chatgpt',
                occurredAt: '2026-02-27T00:00:00.000Z',
            },
        ];
        const result = (0, engine_1.computeSlopScore)(events, undefined, now);
        strict_1.default.equal(result.slop_score, 35);
        strict_1.default.deepEqual(result.analyzed_commits[0]?.flags, ['ai_keyword']);
        strict_1.default.equal(result.top_signals[0], 'Commits with AI-attribution hints');
    });
    (0, node_test_1.it)('ignores merge commits for AI attribution scoring', () => {
        const now = new Date('2026-02-28T00:00:00.000Z');
        const events = [
            {
                id: 'a',
                type: 'commit',
                repo: 'torvalds/uemacs',
                sha: '77804e9',
                message: 'Partial merge with cleanups from PR #55 using Claude AI that are clear improvements.',
                occurredAt: '2026-02-25T00:00:00.000Z',
                additions: 12,
                deletions: 60,
                isMerge: true,
            },
        ];
        const result = (0, engine_1.computeSlopScore)(events, undefined, now);
        strict_1.default.equal(result.slop_score, 0);
        strict_1.default.deepEqual(result.analyzed_commits[0]?.flags, []);
    });
    (0, node_test_1.it)('does not classify merge commits as churn storm', () => {
        const now = new Date('2026-02-28T00:00:00.000Z');
        const events = [
            {
                id: 'a',
                type: 'commit',
                repo: 'yinwm/picoclaw',
                sha: '5b96923',
                message: 'Merge pull request #877 from sipeed/refactor/channel-system',
                occurredAt: '2026-02-27T00:00:00.000Z',
                additions: 10926,
                deletions: 1608,
                isMerge: true,
            },
        ];
        const result = (0, engine_1.computeSlopScore)(events, undefined, now);
        strict_1.default.equal(result.slop_score, 0);
        strict_1.default.equal(result.analyzed_commits[0]?.flags.includes('high_churn'), false);
        strict_1.default.equal(result.top_signals.includes('Suspicious velocity spikes'), false);
        strict_1.default.equal(result.top_signals.includes('Code churn that screams generate-paste-pray'), false);
    });
});
(0, node_test_1.describe)('mapScoreToTier', () => {
    (0, node_test_1.it)('maps score to tier boundaries', () => {
        strict_1.default.equal((0, tier_1.mapScoreToTier)(5), 'The Artisanal Masochist');
        strict_1.default.equal((0, tier_1.mapScoreToTier)(25), 'The Tab-Key Athlete');
        strict_1.default.equal((0, tier_1.mapScoreToTier)(45), 'The LLM Diplomat');
        strict_1.default.equal((0, tier_1.mapScoreToTier)(70), 'The Agent Supervisor');
        strict_1.default.equal((0, tier_1.mapScoreToTier)(99), 'The Unsupervised Slop Machine');
    });
});
