import type { ContributionEvent } from '../types'
import { DEFAULT_SCORING_CONFIG, type ScoringConfig } from './config'
import { mapScoreToTier } from './tier'

const AI_KEYWORDS = [
  'copilot',
  'github copilot',
  'cursor',
  'claude',
  'devin',
  'generated by',
  'chatgpt',
  'openai',
]

const PROMPT_CRUMBS = [
  'as an ai language model',
  "here's the",
  "sure, here's",
  'let me know if you',
  'i cannot',
  "i can't",
]

export type SignalResult = {
  key: string
  label: string
  score: number
  weight: number
  contribution: number
}

export type SlopScoreResult = {
  slop_score: number
  tier: string
  confidence: 'low' | 'medium' | 'high'
  top_signals: string[]
  scoring_window: string
}

const clamp = (value: number, min = 0, max = 100) =>
  Math.min(max, Math.max(min, value))

const getRecencyWeight = (
  occurredAt: string,
  now: Date,
  config: ScoringConfig,
) => {
  const occurred = new Date(occurredAt)
  if (Number.isNaN(occurred.getTime())) {
    return 0
  }
  const diffDays = (now.getTime() - occurred.getTime()) / (1000 * 60 * 60 * 24)
  for (const bucket of config.recencyBuckets) {
    if (diffDays <= bucket.days) {
      return bucket.weight
    }
  }
  return 0
}

const computeWeightedRatio = (
  matches: Array<{ weight: number }>,
  totalWeight: number,
) => {
  if (totalWeight === 0) {
    return 0
  }
  const matchWeight = matches.reduce((sum, match) => sum + match.weight, 0)
  return (matchWeight / totalWeight) * 100
}

const genericMessage = (message: string) => {
  const trimmed = message.trim().toLowerCase()
  if (trimmed.length <= 6) {
    return true
  }
  return [
    'fix',
    'update',
    'wip',
    'cleanup',
    'chore',
    'tweak',
    'refactor',
  ].includes(trimmed)
}

const getDayKey = (occurredAt: string) =>
  new Date(occurredAt).toISOString().slice(0, 10)

const computeConfidence = (
  eventCount: number,
  statsCoverage: number,
): 'low' | 'medium' | 'high' => {
  if (eventCount < 5 || statsCoverage < 0.3) {
    return 'low'
  }
  if (eventCount < 15 || statsCoverage < 0.6) {
    return 'medium'
  }
  return 'high'
}

export const computeSlopScore = (
  events: ContributionEvent[],
  config: ScoringConfig = DEFAULT_SCORING_CONFIG,
  now: Date = new Date(),
): SlopScoreResult => {
  const weightedEvents = events
    .map((event) => ({
      event,
      weight: getRecencyWeight(event.occurredAt, now, config),
    }))
    .filter((item) => item.weight > 0)

  const totalWeight = weightedEvents.reduce((sum, item) => sum + item.weight, 0)

  const statsEvents = weightedEvents.filter(
    (item) =>
      item.event.additions !== undefined || item.event.deletions !== undefined,
  )
  const statsCoverage =
    weightedEvents.length === 0 ? 0 : statsEvents.length / weightedEvents.length

  const aiKeywordMatches = weightedEvents.filter((item) =>
    AI_KEYWORDS.some((keyword) =>
      item.event.message.toLowerCase().includes(keyword),
    ),
  )

  const promptCrumbMatches = weightedEvents.filter((item) =>
    PROMPT_CRUMBS.some((crumb) =>
      item.event.message.toLowerCase().includes(crumb),
    ),
  )

  const aiKeywordScore = computeWeightedRatio(aiKeywordMatches, totalWeight)
  const promptCrumbScore = computeWeightedRatio(promptCrumbMatches, totalWeight)

  const dailyChanges = new Map<string, number>()
  statsEvents.forEach((item) => {
    const changes = (item.event.additions ?? 0) + (item.event.deletions ?? 0)
    if (changes === 0) {
      return
    }
    const key = getDayKey(item.event.occurredAt)
    const current = dailyChanges.get(key) ?? 0
    dailyChanges.set(key, current + changes * item.weight)
  })
  const maxDailyChanges = Math.max(0, ...dailyChanges.values())
  const velocityScore = clamp(
    ((maxDailyChanges - config.thresholds.velocitySpike) / 1400) * 100,
  )

  const largeGenericMatches = statsEvents.filter((item) => {
    const changes = (item.event.additions ?? 0) + (item.event.deletions ?? 0)
    return (
      changes >= config.thresholds.largeChange &&
      genericMessage(item.event.message)
    )
  })
  const totalLargeEligible = statsEvents.filter((item) => {
    const changes = (item.event.additions ?? 0) + (item.event.deletions ?? 0)
    return changes >= config.thresholds.largeChange
  })
  const apathyScore = computeWeightedRatio(
    largeGenericMatches,
    totalLargeEligible.reduce((sum, item) => sum + item.weight, 0),
  )

  const churnMatches = statsEvents.filter((item) => {
    const additions = item.event.additions ?? 0
    const deletions = item.event.deletions ?? 0
    return (
      additions >= config.thresholds.churnAdditions &&
      deletions >= config.thresholds.churnDeletions
    )
  })
  const churnScore = computeWeightedRatio(
    churnMatches,
    statsEvents.reduce((sum, item) => sum + item.weight, 0),
  )

  const signalResults: SignalResult[] = [
    {
      key: 'ai_keywords',
      label: 'Commit messages mention AI tools',
      score: aiKeywordScore,
      weight: config.weights.ai_keywords,
      contribution: aiKeywordScore * config.weights.ai_keywords,
    },
    {
      key: 'prompt_crumbs',
      label: 'Prompt-like crumbs in commit messages',
      score: promptCrumbScore,
      weight: config.weights.prompt_crumbs,
      contribution: promptCrumbScore * config.weights.prompt_crumbs,
    },
    {
      key: 'velocity_volume',
      label: 'Big change spikes in short windows',
      score: velocityScore,
      weight: config.weights.velocity_volume,
      contribution: velocityScore * config.weights.velocity_volume,
    },
    {
      key: 'apathy_ratio',
      label: 'Large commits with tiny or generic messages',
      score: apathyScore,
      weight: config.weights.apathy_ratio,
      contribution: apathyScore * config.weights.apathy_ratio,
    },
    {
      key: 'churn',
      label: 'High-addition + high-deletion churn',
      score: churnScore,
      weight: config.weights.churn,
      contribution: churnScore * config.weights.churn,
    },
  ]

  const weightedScore = signalResults.reduce(
    (sum, signal) => sum + signal.contribution,
    0,
  )

  const slopScore = clamp(Math.round(weightedScore))
  const confidence = computeConfidence(weightedEvents.length, statsCoverage)
  const tier = mapScoreToTier(slopScore)

  const topSignals = signalResults
    .filter((signal) => signal.score > 0)
    .sort((a, b) => b.contribution - a.contribution)
    .slice(0, 3)
    .map((signal) => signal.label)

  if (topSignals.length === 0) {
    topSignals.push('Low signal density in the recent activity window')
  }

  return {
    slop_score: slopScore,
    tier,
    confidence,
    top_signals: topSignals,
    scoring_window: 'last 180 days',
  }
}
