import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import type { ContributionEvent } from '../types'
import { computeSlopScore } from './engine'
import { mapScoreToTier } from './tier'

describe('computeSlopScore', () => {
  it('applies recency weighting and produces deterministic score', () => {
    const now = new Date('2026-02-23T00:00:00.000Z')
    const events: ContributionEvent[] = [
      {
        id: 'a',
        type: 'commit',
        repo: 'octo/repo',
        sha: 'a',
        message: 'feat: generated by copilot',
        occurredAt: '2026-02-20T00:00:00.000Z',
      },
      {
        id: 'b',
        type: 'commit',
        repo: 'octo/repo',
        sha: 'b',
        message: 'refactor: cleanup',
        occurredAt: '2026-02-20T00:00:00.000Z',
      },
      {
        id: 'c',
        type: 'commit',
        repo: 'octo/repo',
        sha: 'c',
        message: 'docs: generated by chatgpt',
        occurredAt: '2025-10-20T00:00:00.000Z',
      },
    ]

    const result = computeSlopScore(events, undefined, now)
    assert.equal(result.slop_score, 20)
    assert.equal(result.confidence, 'low')
  })

  it('does not flag technical cursor mentions as AI evidence', () => {
    const now = new Date('2026-02-28T00:00:00.000Z')
    const events: ContributionEvent[] = [
      {
        id: 'a',
        type: 'commit',
        repo: 'torvalds/uemacs',
        sha: '8bd72de',
        message:
          'Always call update() if the buffer is marked for refresh. In particular, the cursor location affects scrolling behavior.',
        occurredAt: '2026-02-25T00:00:00.000Z',
        additions: 1,
        deletions: 1,
      },
    ]

    const result = computeSlopScore(events, undefined, now)
    assert.equal(result.slop_score, 0)
    assert.deepEqual(result.analyzed_commits[0]?.flags, [])
  })

  it('does not flag plain tool mentions without attribution context', () => {
    const now = new Date('2026-02-28T00:00:00.000Z')
    const events: ContributionEvent[] = [
      {
        id: 'a',
        type: 'commit',
        repo: 'dollspace-gay/chainlink',
        sha: 'b842e80',
        message:
          'make chainlink reminder hook blocking to force claude to use it',
        occurredAt: '2026-02-08T00:00:00.000Z',
      },
    ]

    const result = computeSlopScore(events, undefined, now)
    assert.equal(result.slop_score, 0)
    assert.deepEqual(result.analyzed_commits[0]?.flags, [])
  })

  it('scores contextual AI usage as medium evidence', () => {
    const now = new Date('2026-02-28T00:00:00.000Z')
    const events: ContributionEvent[] = [
      {
        id: 'a',
        type: 'commit',
        repo: 'octo/repo',
        sha: 'a',
        message: 'refactor parser using claude for an initial draft',
        occurredAt: '2026-02-27T00:00:00.000Z',
      },
    ]

    const result = computeSlopScore(events, undefined, now)
    assert.equal(result.slop_score, 21)
    assert.deepEqual(result.analyzed_commits[0]?.flags, ['ai_keyword'])
    assert.equal(result.top_signals[0], 'commits with AI-attribution hints')
  })

  it('scores explicit AI attribution as strong evidence', () => {
    const now = new Date('2026-02-28T00:00:00.000Z')
    const events: ContributionEvent[] = [
      {
        id: 'a',
        type: 'commit',
        repo: 'octo/repo',
        sha: 'a',
        message: 'docs: generated by chatgpt',
        occurredAt: '2026-02-27T00:00:00.000Z',
      },
    ]

    const result = computeSlopScore(events, undefined, now)
    assert.equal(result.slop_score, 35)
    assert.deepEqual(result.analyzed_commits[0]?.flags, ['ai_keyword'])
    assert.equal(result.top_signals[0], 'commits with AI-attribution hints')
  })

  it('ignores merge commits for AI attribution scoring', () => {
    const now = new Date('2026-02-28T00:00:00.000Z')
    const events: ContributionEvent[] = [
      {
        id: 'a',
        type: 'commit',
        repo: 'torvalds/uemacs',
        sha: '77804e9',
        message:
          'Partial merge with cleanups from PR #55 using Claude AI that are clear improvements.',
        occurredAt: '2026-02-25T00:00:00.000Z',
        additions: 12,
        deletions: 60,
        isMerge: true,
      },
    ]

    const result = computeSlopScore(events, undefined, now)
    assert.equal(result.slop_score, 0)
    assert.deepEqual(result.analyzed_commits[0]?.flags, [])
  })

  it('does not flag initial commits as large_generic even with many additions', () => {
    const now = new Date('2026-02-28T00:00:00.000Z')
    const events: ContributionEvent[] = [
      {
        id: 'a',
        type: 'commit',
        repo: 'yyx990803/bun-vs-node-sea-startup',
        sha: 'de8555d',
        message: 'init',
        occurredAt: '2026-02-25T00:00:00.000Z',
        additions: 500,
        deletions: 0,
      },
    ]

    const result = computeSlopScore(events, undefined, now)
    assert.equal(
      result.analyzed_commits[0]?.flags.includes('large_generic'),
      false,
    )
  })

  it('does not classify merge commits as churn storm', () => {
    const now = new Date('2026-02-28T00:00:00.000Z')
    const events: ContributionEvent[] = [
      {
        id: 'a',
        type: 'commit',
        repo: 'yinwm/picoclaw',
        sha: '5b96923',
        message: 'Merge pull request #877 from sipeed/refactor/channel-system',
        occurredAt: '2026-02-27T00:00:00.000Z',
        additions: 10926,
        deletions: 1608,
        isMerge: true,
      },
    ]

    const result = computeSlopScore(events, undefined, now)
    assert.equal(result.slop_score, 0)
    assert.equal(
      result.analyzed_commits[0]?.flags.includes('high_churn'),
      false,
    )
    assert.equal(
      result.top_signals.includes('suspicious velocity spikes'),
      false,
    )
    assert.equal(
      result.top_signals.includes(
        'code churn that screams generate-paste-pray',
      ),
      false,
    )
  })
})

describe('mapScoreToTier', () => {
  it('maps score to tier boundaries', () => {
    assert.equal(mapScoreToTier(0).name, 'the untouched keyboard')
    assert.equal(mapScoreToTier(8).name, 'the untouched keyboard')
    assert.equal(mapScoreToTier(9).name, 'the tab-key athlete')
    assert.equal(mapScoreToTier(22).name, 'the tab-key athlete')
    assert.equal(mapScoreToTier(23).name, 'the prompt-curious')
    assert.equal(mapScoreToTier(40).name, 'the prompt-curious')
    assert.equal(mapScoreToTier(41).name, 'the context window regular')
    assert.equal(mapScoreToTier(60).name, 'the context window regular')
    assert.equal(mapScoreToTier(61).name, 'the delegation economy')
    assert.equal(mapScoreToTier(75).name, 'the delegation economy')
    assert.equal(mapScoreToTier(76).name, 'the fully cooked instance')
    assert.equal(mapScoreToTier(90).name, 'the fully cooked instance')
    assert.equal(mapScoreToTier(91).name, 'the unsupervised slop machine')
    assert.equal(mapScoreToTier(100).name, 'the unsupervised slop machine')
  })

  it('includes taglines for all tiers', () => {
    assert.equal(
      mapScoreToTier(5).tagline,
      'you debug with print statements. respect.',
    )
    assert.equal(
      mapScoreToTier(95).tagline,
      'are they even there? hello? anyone home?',
    )
  })
})
