import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { labNotes } from '../../data/lab-notes'
import { LabNotesLedger } from './lab-notes-view'

describe('LabNotesLedger', () => {
  it('renders versioned media entries with commit metadata and controls', () => {
    const html = renderToStaticMarkup(
      createElement(LabNotesLedger, { entries: labNotes }),
    )

    assert.ok(html.includes('v0.0.2'))
    assert.ok(html.includes('/changelogs/slop-v0.0.2.mp4'))
    assert.ok(html.includes('latest commit reel'))
    assert.ok(html.includes('id="note-v0-0-2"'))
    assert.ok(html.includes('initial release'))
    assert.ok(html.includes('aria-label="play video"'))
    assert.ok(html.includes('aria-label="toggle fullscreen"'))
    assert.ok(html.includes('[a149717]'))
    assert.ok(html.includes('generated by ai'))
    assert.equal(html.match(/v0\.0\.1/g)?.length ?? 0, 1)
    assert.ok(html.indexOf('[8e448fa]') < html.indexOf('initial release'))
    assert.ok(html.indexOf('[cd72368]') < html.indexOf('initial release'))
  })
})
